name: realtime_stock_monitoring
description: "실시간 관심 종목 모니터링 앱"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  cupertino_icons: ^1.0.8
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  provider: ^6.1.2
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
